version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - "type: dependency-upgrade"
  ignore:
  - dependency-name: io.cucumber:cucumber-core
    versions:
    - ">= 5.a, < 6"
  - dependency-name: io.cucumber:cucumber-java
    versions:
    - ">= 5.a, < 6"
  - dependency-name: io.cucumber:cucumber-java8
    versions:
    - ">= 5.a, < 6"
  - dependency-name: io.cucumber:cucumber-junit
    versions:
    - ">= 5.a, < 6"
  - dependency-name: io.cucumber:cucumber-spring
    versions:
    - ">= 5.a, < 6"
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - ">= 2.0.a, < 2.1"
  - dependency-name: org.springframework.boot:spring-boot-dependencies
    versions:
    - ">= 2.1.a, < 2.2"
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - ">= 2.1.a, < 2.2"
  - dependency-name: org.springframework.boot:spring-boot-maven-plugin
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
  - dependency-name: com.auth0:java-jwt
    versions:
    - 3.12.1
    - 3.13.0
    - 3.14.0
  - dependency-name: mysql:mysql-connector-java
    versions:
    - 8.0.23
  - dependency-name: org.ow2.asm:asm
    versions:
    - "9.0"
  - dependency-name: org.apache.tomcat:tomcat-juli
    versions:
    - 9.0.35
  - dependency-name: org.apache.tomcat:tomcat-jdbc
    versions:
    - 9.0.35
  - dependency-name: org.apache.tomcat:tomcat-annotations-api
    versions:
    - 9.0.35
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-websocket
    versions:
    - 9.0.35
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-jasper
    versions:
    - 9.0.35
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-el
    versions:
    - 9.0.35
  - dependency-name: org.apache.tomcat.embed:tomcat-embed-core
    versions:
    - 9.0.35
