#! /bin/sh

set -e

ln -sf /usr/share/libresonic/libresonic.sh /usr/bin/libresonic

chmod 750 /var/libresonic

# Clear jetty cache.
rm -rf /var/libresonic/jetty

# Configure Libresonic service.
update-rc.d libresonic defaults 99

# Start Libresonic service.
invoke-rc.d libresonic start
